### ISSUE TITLE
mpMap2 install ERROR

### ISSUE THREAD

**Issue by YuntaoTan** [rohan-shah/mpMap2#2]
hi,
 rohan-shah,
when i install mpMap2, i get following error. can you help me. thank you.
 `$ R CMD INSTALL mpMap2-0.0.4.tar.gz
untar2(tarfile, files, list, exdir, restore_times)里有警告:
  skipping pax global extended headers
* installing to library ‘/home/tanyt/R/x86_64-unknown-linux-gnu-library/3.1’
* installing *source* package ‘mpMap2’ ...
** libs
g++ -std=c++0x -I/share/genome/biosoft/R/3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/share/genome/biosoft/R/3.1.1/lib64/R/library/Rcpp/include"  -I. -DUSE_OPENMP -fopenmp -fpic  -g -O2 -c alleleDataErrors.cpp -o alleleDataErrors.o
g++ -std=c++0x -I/share/genome/biosoft/R/3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/share/genome/biosoft/R/3.1.1/lib64/R/library/Rcpp/include"  -I. -DUSE_OPENMP -fopenmp -fpic  -g -O2 -c arsa.cpp -o arsa.o
arsa.cpp: In function ‘SEXPREC* arsaExportedR(SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*)’:
arsa.cpp:177: 错误：expected primary-expression before ‘[’ token
arsa.cpp:177: 错误：expected primary-expression before ‘]’ token
arsa.cpp:177: 错误：expected primary-expression before ‘unsigned’
arsa.cpp:177: 错误：expected primary-expression before ‘unsigned’
arsa.cpp:177: 错误：expected ‘,’ or ‘;’ before ‘{’ token
make: *** [arsa.o] 错误 1
ERROR: compilation failed for package ‘mpMap2’
* removing ‘/home/tangyt/R/x86_64-unknown-linux-gnu-library/3.1/mpMap2`
Then, i try to install from cmake.
make && make install
`[  5%] Building CXX object src/CMakeFiles/mpMap2.dir/crc32.cpp.o
[  7%] Building CXX object src/CMakeFiles/mpMap2.dir/estimateRF.cpp.o
In file included from /share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/markerPatternsToUniqueValues.h:7,
                 from /share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/estimateRFSpecificDesign.h:5,
                 from /share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/estimateRF.cpp:4:
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp:16: 错误：expected ‘,’ or ‘...’ before ‘&&’ token
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp:16: 错误：无效的构造函数：您要的可能是‘rowMajorMatrix<T> (const rowMajorMatrix<T>&)’
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp:19: 错误：expected ‘,’ or ‘...’ before ‘&&’ token
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp: In member function ‘rowMajorMatrix<T>& rowMajorMatrix<T>::operator=(rowMajorMatrix<T>)’:
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp:21: 错误：‘other’在此作用域中尚未声明
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp: At global scope:
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp:78: 错误：expected ‘,’ or ‘...’ before ‘&&’ token
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp:78: 错误：无效的构造函数：您要的可能是‘xMajorMatrix<T> (const xMajorMatrix<T>&)’
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp:81: 错误：expected ‘,’ or ‘...’ before ‘&&’ token
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp: In member function ‘xMajorMatrix<T>& xMajorMatrix<T>::operator=(xMajorMatrix<T>)’:
/share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/matrices.hpp:83: 错误：‘other’在此作用域中尚未声明
In file included from /share/nas1/tanyt/develop/MuiltFamily/mpMap2-0.0.4/src/estimateRFSpecificDesign.h:5,`

**Comment by rohan-shah** [comment]
I'll don't have a Linux machine to test on until Monday. Can you give me your gcc version, and can you also try and install from the git version.

**Comment by rohan-shah** [comment]
All the lines listed are points at which relatively recent c++ features are used - anonymous functions and move semantics. I suspect you have an ancient version of gcc.
