### ISSUE TITLE
mpMap2 install error (using standard tools/ windows) 

### ISSUE THREAD

**Issue by TallyWright** [rohan-shah/mpMap2#3]
To use mpmapinteractive2 - I've updated to R version 3.5.2 (2018-12-20) and I'm trying to reinstall mpMap2.  I'm using the same method I used for the older R version. However, the package compile now fails. I have tested with Rtools version 33 and 35. The same error appears. 

I'm using
devtools :: install_github("rohan-shah/mpMap2")  

The output is: 
> devtools :: install_github("rohan-shah/mpMap2")
Downloading GitHub repo rohan-shah/mpMap2@master
√  checking for file 'C:\Users\x991625\AppData\Local\Temp\RtmpAZSf9s\remotes498c71623fcc\rohan-shah-mpMap2-766d738/DESCRIPTION' ... 
-  preparing 'mpMap2': (488ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories (798ms)
-  building 'mpMap2_0.0.5.tar.gz'
   
Installing package into ‘C:/Users/x991625/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'mpMap2' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG       -I. -DUSE_OPENMP -fopenmp   -O2 -Wall  -mtune=generic -c alleleDataErrors.cpp -o alleleDataErrors.o
In file included from alleleDataErrors.cpp:1:0:
alleleDataErrors.h:3:18: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
                  ^
compilation terminated.
make: *** [alleleDataErrors.o] Error 1
ERROR: compilation failed for package 'mpMap2'
* removing 'C:/Users/x991625/Documents/R/win-library/3.5/mpMap2'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/x991625/AppData/Local/Temp/RtmpAZSf9s/file498c3a3976ef/mpMap2_0.0.5.tar.gz’ had non-zero exit status

Thanks!

**Comment by rohan-shah** [comment]
I see the same error on travis-ci, looking into this soon.....

**Comment by rohan-shah** [comment]
I accidentally deleted a line from the DESCRIPTION file, oops! It's now updated on github, and I will put out a new release when I get the chance. In the meantime, can you build it off git and confirm that it works?
