### ISSUE TITLE
User instruction request

### ISSUE THREAD

**Issue by GuoanQi1996** [rohan-shah/mpMap2#5]
Dear developers,
  Thanks for providing such a useful tool mpMap(2).
  I am trying to generate a simulated MAGIC population from 16 parent lines using mpMap(2), is there any instructions for this? Maybe I 've missed something, I did not find any manual available on the internet.

 Appreciate your help.

**Comment by rohan-shah-nearmap** [comment]
There is a function called `sixteenParentPedigreeRandomFunnels ` which, as the name suggests, simulates an individual from a randomly chosen funnel. See also `mpMap2.Rnw` in repository `rohan-shah/mpMap2Paper`. Assuming you already know how to simulate four and eight-parent crosses, the extension to sixteen should hopefully be simple. 

I could give you more detailed instructions, but it'll take quite a while for me to find time (and re-familiarise myself with the code).

**Comment by GuoanQi1996** [comment]
Really appreciate your quick response and help.

I did not find the mpMap2.Rnw before so, it is quite uneasy to read the description of each function and try to figure out the connection among them. I'll dig into it to see if I can work my problems out.

Thanks again.
